## Workflow: Main
## Contributors: Ulrich Bergmann 
## (GitHub: @bergmul, Email: ulrich.bergmann@gmail.com)


##############################################
## Misc
##############################################


# Run R with the following options
# do not save workspace after session
# do not restore previously saved objects
# print all information while running the process

run_R = "Rscript --no-save --no-restore --verbose"


##############################################
## Get input filenames
##############################################


TARGETS = [ "170601_03", "170601_04", "170601_05" ]


##############################################
## Build Rules
##############################################


rule bundleData:
    input:
        script = "input/code/bundle-data.R",
        data = expand("output/data/sessions/{iFile}.csv", iFile = TARGETS)
    output:
        "output/data/bundled-data.csv"
    params:
        "output/data/sessions"
    shell:
        "{run_R} {input.script} {params} {output}"


rule convert2csv:
    input:
        script  = "input/code/data-cleaning.R",
        rawData = "input/raw-data/{iFile}.xls"
    output:
        "output/data/sessions/{iFile}.csv"
    shell:
        "{run_R} {input.script} {input.rawData} {output}"


##############################################
## Cleaning Rules
##############################################


rule clean:
    shell:
        "find ./output -type f -delete; \
        rm -fv *.pdf"
