---
title: "Examples Slot 6"
author: "Dora Simon"
date: "September 10, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Example

```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(ggplot2)
diamonds_df<-as.data.frame(diamonds)
head(diamonds_df)
```



## Example

```{r, echo=TRUE, message=FALSE, warning=FALSE}
summary(diamonds_df$carat)

```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data=diamonds_df)
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data=diamonds_df) + geom_point(mapping=aes(x=carat, y=price))
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_point(mapping = aes(x = carat, y = price, color = clarity))
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_point(mapping = aes(x = carat, y = price, alpha = clarity))
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_point(mapping = aes(x = carat, y = price, 
                           color = clarity > 'VS2'))
```

## Example

```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_point(mapping = aes(x = carat, y = price)) +
  facet_wrap(~ cut, nrow=2)
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_point(mapping = aes(x = carat, y = price)) +
  facet_grid(clarity ~ cut)
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_smooth(mapping = aes(x = carat, y = price))
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_smooth(mapping = aes(x = carat, y = price, color=cut))
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df, mapping = aes(x = carat, y = price)) +
  geom_point(size = 0.2, alpha = 0.5) +
  geom_smooth()
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_bar(mapping = aes(x=clarity))
```

## Example

```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df, mapping = aes(x=clarity)) +
  geom_bar()
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_bar(mapping = aes(x = cut, fill = clarity), 
           position = "fill")
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_bar(mapping = aes(x = cut, fill = clarity), 
           position = "dodge")
```

## Example

```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_point(mapping = aes(x = carat, y = price)) +
  coord_trans(x = "log", y = "log")
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_point(mapping = aes(x = carat, y = price, color = clarity)) +
  labs(title = "Relationship between weight and price of diamonds",
       x = "Weight in carat",
       y = "Price in dollars",
       color = "Clarity")
```

## Example


```{r, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4, dev='svg'}
ggplot(data = diamonds_df) +
  geom_point(mapping = aes(x = carat, y = price, color = clarity)) +
  scale_x_continuous(breaks = seq(0, 5, 0.5)) +
  scale_color_discrete(labels = seq(1, 8))
```
